### ISSUE TITLE
error

### ISSUE THREAD

**Issue by mumuwanglin** [chenhuimao/HMLLDB#1]
[HMLLDB] Waiting...
[HMLLDB] error: error: Execution was interrupted, reason: EXC_BAD_ACCESS (code=1, address=0x1000007ad).
The process has been returned to the state before expression evaluation.
[HMLLDB] Traceback(filename='/Users/mumu/HMLLDB/commands/HMClassInfoCommands.py', lineno=524, function='findMethod', code_context=['    result = HM.evaluateExpressionValue(command_script).GetObjectDescription()\n'], index=0)
[HMLLDB] None

**Comment by chenhuimao** [comment]
遇到错误的处理流程参考README.md。
Execution was interrupted这种错误，一般重启Xcode就好了，记得是点击Pause program execution进入lldb模式而不是命中断点。
如果还不行，请把fmethod命令的完整输入（含参数）贴出来。并且执行environment命令，贴出其输出内容帮助判断。
